
# This file was generated by the {rix} R package v0.1.2 on Mon Aug 14 17:44:28 2023
# with following call:
# >rix::rix(r_pkgs = c("tarchetypes",
#  > "ggbeeswarm",
#  > "conflicted",
#  > "tidyverse",
#  > "distill",
#  > "janitor",
#  > "targets",
#  > "polite",
#  > "scales",
#  > "rvest",
#  > "fs"),
#  > ide = "rstudio",
#  > overwrite = TRUE,
#  > r_ver = "81b970640e56a5c07a336d2c05018b0c9bf57a51")
# It uses nixpkgs' revision 81b970640e56a5c07a336d2c05018b0c9bf57a51 for reproducibility purposes
# which will install R version current
# Report any issues to https://github.com/b-rodrigues/rix
    { pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/81b970640e56a5c07a336d2c05018b0c9bf57a51.tar.gz") {} }:

      with pkgs;

      let
      my-r = rWrapper.override {
        packages = with rPackages; [
          tarchetypes ggbeeswarm conflicted tidyverse distill janitor targets polite scales rvest fs
           
        ];
      };
  my-rstudio = rstudioWrapper.override {
    packages = with rPackages; [
                      tarchetypes ggbeeswarm conflicted tidyverse distill janitor targets polite scales rvest fs
                       
        ];
};
      in
      mkShell {
        buildInputs = [
          my-r
          my-rstudio
          ];
      }
